#kams
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: hpa
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector: 
    matchLabels:
      app: hp
  template:
    metadata:
      # name: hpa
      labels:  
        app: hp
    spec:
     containers:
     - name: hpabucket
       image: mylandmarktech/hello:1
       ports:
       - containerPort: 80
         #resources:
         #requests: 
         # cpu: 50mi
         # memory: 20m
         # limits:
         # cpu: 50mi
             #memory: 20m

---
#kams
apiVersion: v1
kind: Service
metadata:
  name: hpasvc
spec:
  type: NodePort
  selector:
    app: hp
  ports:
  - port: 90
    targetPort: 80
    nodePort: 32400
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
     name: memory
     target:
      type: Utilization
      averageUtilization: 40

