apiVersion: apps/v1
kind: Deployment
metadata:
  name: ringapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ring
  template:
    metadata:
      labels:
        app: ring
    spec:
      containers:
      - name: ringappcontainer
        image: mylandmarktech/spring-boot-mongo
        #resources:
         # requests:
          #  cpu: 200m
           # memory: 256Mi
          #limits:
           # memory: "512Mi"
            #cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ringsvc
spec:
  type: NodePort
  selector:
    app: ring
  ports:
  - port: 80
    targetPort: 8080
