kind: Secret  
apiVersion: v1    
metadata:
  name: springappsecret
type: Opaque
stringData:                   # We can define multiple key value pairs.
  db-password: ZGV2ZGJAMTIz
    # echo -n <password> | base64  
