apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapprc
  namespace: dev
  labels: 
    app: myapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      name: tesla
      labels:
        app: myapp
    spec:
      containers:
      - name: mavenapp
        image: mylandmarktech/hello
        ports:
        - containerPort: 8080

